### ISSUE TITLE
Causes segmentation fault

### ISSUE THREAD

**Issue by aminya** [Unbuttun/is-url-online#39]
I tried to use this package, but it causes a segmentation fault. I can't find the root cause of this.

https://github.com/aminya/setup-cpp/runs/7719207561?check_suite_focus=true#step:9:49

**Comment by spa5k** [comment]
@aminya checked your repo and it doesn't seems like you are using my package at all, `is-url-online`, and also i don't think it can cause any of segmentation fault as its not really doing much.

**Comment by aminya** [comment]
It was caused by using this package. It could be because of Parcel not being to bundle this package correctly. 

https://github.com/aminya/setup-cpp/pull/114/commits/232af3c14194e97206060bf986965c2017dda647

**Comment by spa5k** [comment]
Maybe it's related to some native stuff, will look into it, probably the node-fetch-native package is resulting in error.

**Comment by aminya** [comment]
You can also use the built-in https package. See this for example:
https://github.com/aminya/setup-cpp/blob/master/packages/get-works/src/index.ts

I can make a PR if you like.

**Comment by spa5k** [comment]
Is this https module supported by both node and browsers?

**Comment by spa5k** [comment]
Looks like it's available, can you do the PR?
